DOCS-5226 Azure DevOps Extension Edits
DataDog/datadog-ci-azure-devops pull request #48
Opened 2023-04-12 23:01 UTC by alai97

## Context

Adds a site region shortcode in the doc page.

## Motivation

DOCS-5226

## Preview

2023-04-13 08:35 UTC, etnbrd requested changes
Same as https://github.com/DataDog/synthetics-ci-github-action/pull/127#pullrequestreview-1382910107

2023-04-18 22:24 UTC, alai97 commented on README.md
> +| `datadogSite`        | _optional_  | The [Datadog site][11] when using the `apiAppKeys` authentication type. Your Datadog site is {{< region-param key="dd_site" code="true" >}}. **Default:** `datad
```suggestion
| `datadogSite`        | _optional_  | The [Datadog site][11] when using the `apiAppKeys` authentication type. **Default:** `datadoghq.com`.                                                                                                                                           |
```

2023-04-19 08:02 UTC, etnbrd requested changes

2023-04-20 07:18 UTC, etnbrd approved these changes
🚀

2023-04-21 20:05 UTC, rtrieu approved these changes
Looks good!

2023-04-21 20:44 UTC, merged